# Generated by Django 5.0.7 on 2024-07-26 00:39

import django.db.models.deletion
import medhistory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedEspeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[medhistory.validators.validate_no_numbers, medhistory.validators.validate_no_symbols, medhistory.validators.validate_max_two_words])),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[medhistory.validators.validate_no_numbers, medhistory.validators.validate_no_symbols, medhistory.validators.validate_max_two_words])),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[medhistory.validators.validate_no_numbers, medhistory.validators.validate_no_symbols, medhistory.validators.validate_max_two_words])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('medespeciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medhistory.medespeciality')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[medhistory.validators.validate_no_numbers, medhistory.validators.validate_no_symbols, medhistory.validators.validate_max_two_words])),
                ('history', models.TextField()),
                ('age', models.IntegerField(max_length=2, validators=[medhistory.validators.validate_age, medhistory.validators.validate_number])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, validators=[medhistory.validators.validate_number])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medhistory.specie')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medhistory.veterinarian')),
            ],
        ),
    ]
