# Generated by Django 5.0.7 on 2024-07-26 00:54

import medhistory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[medhistory.validators.validate_age, medhistory.validators.validate_number]),
        ),
    ]
